name: Test and verify VDS Project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-and-verify:
    name: Test and verify
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install GTest library
      run: |
        sudo apt-get install libgtest-dev
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make
        sudo cp lib/*.a /usr/lib
        sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a
        sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a

    - name: Install Graphviz library
      run: sudo apt-get install graphviz-dev

    - name: Install Boost 1.84.0 library
      run: |
        wget https://boostorg.jfrog.io/artifactory/main/release/1.84.0/source/boost_1_84_0.tar.bz2
        tar --bzip2 -xf boost_1_84_0.tar.bz2
        cd boost_1_84_0
        ./bootstrap.sh
        sudo ./b2 install

    - name: Build VDSProject_23Group7
      run: |
        cmake -S . -B build
        cmake --build build

    - name: Test VDSProject_23Group7
      run: ./build/src/test/VDSProject_test

    - name: Verify VDSProject_23Group7 with ISCAS'85 c3540 benchmark
      shell: bash
      run: |
        chmod +x ./src/verify/verify.sh
        ./src/verify/verify.sh -c c3540 -r 10.0 -m 1000000 -t 20s

    - name: Verify VDSProject_23Group7 with ISCAS'85 c432 benchmark
      shell: bash
      run: |
        chmod +x ./src/verify/verify.sh
        ./src/verify/verify.sh -c c432 -r 1.0 -m 100000 -t 10s